# Site settings
title: Héctor Acosta
email: hacost@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software developer Java, Ruby on Rails, Swift - Certified ScrumMaster... 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hacost.github.io/" # the base hostname & protocol for your site
twitter_username: h_acosta
github_username:  hacost

# Build settings
markdown: kramdown
